build(angular): update to 15.2
shiftcode/sc-ng-commons-public pull request #19
Opened 2023-05-05 07:05 UTC by simonmumenthaler

closes #18

2023-10-18 07:35 UTC, michaelwittwer commented
@simonmumenthaler can we release this. I think we now have different projects depending on it, the ones I know:
- https://github.com/shiftcode/ed-map

/cc @arisjavet

2023-10-18 13:44 UTC, michaelwittwer reviewed
I would propose to remove all the modules which were deprecated in past versions, since we want the Standalone pattern to be promoted in our projects, right?

2023-10-18 14:01 UTC, michaelwittwer requested changes

2023-10-19 09:51 UTC, simonmumenthaler commented on libs/components/src/lib/flying-focus/flying-focus.component.ts
>      this.docEl = doc.documentElement
¯\_(ツ)_/¯

2023-10-19 13:21 UTC, michaelwittwer approved these changes

2023-10-19 13:31 UTC, merged