#6 upgrade to angular 14
shiftcode/sc-ng-commons-public pull request #8
Opened 2022-06-02 20:16 UTC by simonmumenthaler

2022-06-03 05:05 UTC, simonmumenthaler commented
todo before merging: upgrade `@angular-builders/jest` to v14

2022-06-14 07:05 UTC, michaelwittwer requested changes
see one minor change request

2022-06-14 07:07 UTC, simonmumenthaler commented on package.json
>      "@angular-builders/jest": "~13.0.2",
happened while you were reviewing.
Wasn't available when I did the initial upgrade

2022-06-14 07:13 UTC, michaelwittwer submitted a review, later dismissed

2022-10-17 14:29 UTC, michaelwittwer approved these changes

2022-10-17 14:29 UTC, merged